# Generated by Django 2.0 on 2018-04-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_originaltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaltext',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
