# Generated by Django 2.0 on 2018-04-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_originaltext_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField()),
                ('translation', models.TextField()),
                ('user_translation', models.TextField()),
                ('from_language', models.TextField()),
                ('to_language', models.TextField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
